-- Migrar datos de los lotes de ejemplo a la base de datos

-- Primero necesitamos obtener los IDs de farmer, farm y variety
-- Asumiendo que ya existen en la BD, sino hay que crearlos primero

-- Lote AR000147 - Armando Ramirez
INSERT INTO public.coffee_batches (
    batch_id,
    farmer_id,
    farm_id,
    variety_id,
    harvest_date,
    harvest_season,
    harvest_method,
    processing_method,
    drying_method,
    transport_mode,
    roast_date,
    pack_date,
    distribution_date,
    retail_date,
    origin,
    transfer_to_quito,
    storage,
    roast_types,
    transfer_to_shipping,
    destination_country,
    status
) VALUES (
    'AR000147',
    (SELECT id FROM farmers WHERE full_name = 'Armando Ramirez' LIMIT 1),
    (SELECT id FROM farms WHERE name = 'Finca El Mirador' LIMIT 1),
    (SELECT id FROM coffee_varieties WHERE name = 'Typica Mejorada' LIMIT 1),
    '2025-08-15',
    'main',
    'selective',
    'washed',
    'natural',
    'via_terrestre',
    '2025-09-20',
    '2025-09-20',
    '2025-09-20',
    '2025-09-20',
    'Paltas-Olmedo-Vilcabamba',
    'terrestre',
    'Bodega Quito Central',
    'tueste claro - tueste medio',
    'terrestre-marítimo',
    'Japón - Estados Unidos',
    'active'
) ON CONFLICT (batch_id) DO UPDATE SET
    origin = EXCLUDED.origin,
    transfer_to_quito = EXCLUDED.transfer_to_quito,
    storage = EXCLUDED.storage,
    roast_types = EXCLUDED.roast_types,
    transfer_to_shipping = EXCLUDED.transfer_to_shipping,
    destination_country = EXCLUDED.destination_country;

-- Lote PQ000258 - Pablo Quezada
INSERT INTO public.coffee_batches (
    batch_id,
    farmer_id,
    farm_id,
    variety_id,
    harvest_date,
    harvest_season,
    harvest_method,
    processing_method,
    drying_method,
    transport_mode,
    roast_date,
    pack_date,
    distribution_date,
    retail_date,
    origin,
    transfer_to_quito,
    storage,
    roast_types,
    transfer_to_shipping,
    destination_country,
    status
) VALUES (
    'PQ000258',
    (SELECT id FROM farmers WHERE full_name = 'Pablo Quezada' LIMIT 1),
    (SELECT id FROM farms WHERE name = 'Gran Chaparral' LIMIT 1),
    (SELECT id FROM coffee_varieties WHERE name = 'Gesha' LIMIT 1),
    '2025-07-20',
    'main',
    'selective',
    'honey',
    'honey',
    'via_aerea',
    '2025-09-15',
    '2025-09-15',
    '2025-09-16',
    '2025-09-17',
    'Portovelo-Piñas',
    'aéreo',
    'Bodega Quito Norte',
    'tueste medio - tueste medio oscuro',
    'aéreo-marítimo',
    'Corea del Sur - Singapur',
    'active'
) ON CONFLICT (batch_id) DO UPDATE SET
    origin = EXCLUDED.origin,
    transfer_to_quito = EXCLUDED.transfer_to_quito,
    storage = EXCLUDED.storage,
    roast_types = EXCLUDED.roast_types,
    transfer_to_shipping = EXCLUDED.transfer_to_shipping,
    destination_country = EXCLUDED.destination_country;

-- Lote MG000369 - María González (solo en página lotes)
INSERT INTO public.coffee_batches (
    batch_id,
    farmer_id,
    farm_id,
    variety_id,
    harvest_date,
    harvest_season,
    harvest_method,
    processing_method,
    drying_method,
    transport_mode,
    roast_date,
    pack_date,
    distribution_date,
    retail_date,
    status
) VALUES (
    'MG000369',
    (SELECT id FROM farmers WHERE full_name = 'María González' LIMIT 1),
    (SELECT id FROM farms WHERE name = 'La Esperanza' LIMIT 1),
    (SELECT id FROM coffee_varieties WHERE name = 'Bourbon Rosado' LIMIT 1),
    '2025-06-10',
    'main',
    'selective',
    'washed',
    'washed',
    'via_terrestre',
    '2025-09-12',
    '2025-09-12',
    '2025-09-13',
    '2025-09-14',
    'active'
) ON CONFLICT (batch_id) DO UPDATE SET
    roast_date = EXCLUDED.roast_date,
    pack_date = EXCLUDED.pack_date,
    distribution_date = EXCLUDED.distribution_date,
    retail_date = EXCLUDED.retail_date;
